### ISSUE TITLE
Iterator invalidation is ignored

### ISSUE THREAD

**Issue by mmomtchev** [libgeos/geos#490] opened 2021-10-24 17:45 UTC
Windows debug builds of 3.10.0 generate a runtime exception in `MakeValid` because there is an iterator invalidation condition that is ignored

The exception is raised on the following line 
https://github.com/libgeos/geos/blob/2653b5bcc2b1cc88fcd24af593a37825229f5e0e/include/geos/index/strtree/TemplateSTRtree.h#L440

The iterator invalidation happens here (I think):
https://github.com/libgeos/geos/blob/2653b5bcc2b1cc88fcd24af593a37825229f5e0e/include/geos/index/strtree/TemplateSTRtree.h#L478

Normally, and depending on the library/compiler, this is something that is supposed to work (especially since the element is added at the back), but it is contrary to the C++ specification and MSVC will detect it in debug mode (it inserts extra runtime checking) and it will trigger an exception

**Comment by pramsey** [comment] 2021-11-17 20:19
Trying to figure a fix for this:
* have a `childNodes` vector that is built up in the `createParentNodes()` process and then copied into `nodes` vector at each iteration of the `build()` loop? More copying (boo) but separates the vector being iterated on from the additions... 
* start passing around a start iterator and a size instead? (it seems like the end iterator would be the one getting invalidated)

**Comment by dbaston** [comment] 2021-11-17 20:44
The solution may be to not use iterators. This has been floating around in my subconscious for a bit, but it's hard to be motivated to fully rewrite it because there is no practical problem.

**Comment by dbaston** [comment] 2021-11-17 20:46
I would interpret [this](https://stackoverflow.com/a/6442829) to mean that all iterators (start and end) are invalidated whenever we do an insertion.

**Comment by pramsey** [comment] 2021-11-17 20:51
Yeah, it's not an actual problem only a theoretical one (since the vector only grows, never shrinks) and only shows up in debug mode on a single platform. I'm going to Won't Fix this, but note here that PRs are accepted.

**Closed by pramsey** 2021-11-17 20:51 UTC

**Comment by mmomtchev** [comment] 2021-11-18 12:47
@pramsey @dbaston, in theory, the C++ specification allows a runtime to implement an `std::vector` iterator as a pointer, not an index - in this case even adding to the vector can invalidate the pointer, as the whole array can be reallocated, but in practice, no one does that
You can probably add [_ITERATOR_DEBUG_LEVEL=0](https://docs.microsoft.com/en-us/cpp/standard-library/iterator-debug-level?view=msvc-170) to your Windows build (or directly as a `#define` in the source file)

**Comment by mmomtchev** [comment] 2021-11-18 13:55
@pramsey I will submit a PR shortly, `_ITERATOR_DEBUG_LEVEL` has consequences for a library

**Comment by dbaston** [comment] 2021-11-18 14:11
>  in this case even adding to the vector can invalidate the pointer, as the whole array can be reallocated, but in practice, no one does that

But only if the insertion changes the vector's capacity? That is not the case here.
https://en.cppreference.com/w/cpp/container/vector

**Comment by dbaston** [comment] 2021-11-18 14:26
I guess the issue is that we are using `nodes.end()`, which is invalidated on insert even if the capacity is unchanged.

**Comment by mmomtchev** [comment] 2021-11-18 16:28
@dbaston I agree, using `end()` is the problem - here is my tentative fix which simply avoids using it

**Comment by mloskot** [comment] 2021-11-26 10:15
> not an actual problem only a theoretical one (since the vector only grows, never shrinks)

Well, one can argue the code violates the [standard](https://en.cppreference.com/w/cpp/container/vector/emplace_back).

> If the new size() is greater than capacity() then all iterators and references (including the past-the-end iterator) are invalidated. Otherwise only the past-the-end iterator is invalidated.

**Comment by mmomtchev** [comment] 2021-11-26 10:16
@mloskot This is about making the Windows debug build work - not about correctness

**Comment by mloskot** [comment] 2021-11-26 10:19
Well, the bug (yours) report points the C++ spec violation. If the performance of the checks wasn't an issue, the checks would be there regardless of build type.
