### ISSUE TITLE
GEOSCovers() returns 1 instead of 0 for specific polygon ( 3.10.2-1 )

### ISSUE THREAD

**Issue by heriberto-delgado** [libgeos/geos#1163] opened 2024-09-16 15:32 UTC
For the following polygons:

g1: POLYGON(-112.6757810000000006 42.8906250000000000, -112.5000000000000000 42.8906250000000000, -112.5000000000000000 42.7148439999999994, -112.6757810000000006 42.7148439999999994, -112.6757810000000006 42.8906250000000000)

g2: POLYGON(-112.5550941764209369 42.8706444563234967, -112.6649574576715906 42.8706444563234967, -112.6654333021527776 42.8906250000000000, -112.5559332485882322 42.8906250000000000, -112.5550941764209369 42.8706444563234967)

A call to `GEOSCovers(g1, g2)` is returning 1, instead of 0.

g2 is a small rectangle, which lies at the top of g1, a larger rectangle. The top edges of g1 and g2 are touching each other.

![Screenshot 2024-09-16 093054](https://github.com/user-attachments/assets/e105e83d-d74c-4f16-9e56-f5816e282c9c)

Am I doing something wrong here? Or is there something I'm not specifying correctly?

**Comment by dr-jts** [comment] 2024-09-16 16:15
Actually that is the correct result - covers(g1, g2) is TRUE, as evident from the picture (and the fact that g1 is larger than g2).

The problem is that the documentation is incorrect - the definitions of `GEOSCovers` and `GEOSCoveredBy` are reversed.  I'll fix that now.

**Comment by dr-jts** [comment] 2024-09-16 16:38
Fixed by https://github.com/libgeos/geos/commit/d2dcb92e76294ab802bd3d2c26ad5d33d47c06fd

**Closed by dr-jts** 2024-09-16 16:38 UTC
Labels: Bug, Documentation
