### ISSUE TITLE
MultiLineString/Polygon difference runs abnormally slow in some circumstances

### ISSUE THREAD

**Issue by abey79** [libgeos/geos#337] opened 2020-09-21 18:37 UTC
@LoicGoulefert and I ran into a test case where the difference between a MultiLineString and a simple Polygon would yield unusually large processing times (at least many minutes). The MLS contains ~100 lines, including some that are seriously degenerate. However, the polygon intersects only 2 lines, both of which being "normal".

Here is what the data looks like:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/49431240/93776231-a4f81c80-fc23-11ea-999b-4c32c53e70d6.png">

Here are the WKT for the data:
- MultiLineString: [mls_wkt.txt.zip](https://github.com/libgeos/geos/files/5257434/mls_wkt.txt.zip)
- Polygon: [polygon_wkt.txt](https://github.com/libgeos/geos/files/5257435/polygon_wkt.txt)

Unfortunately, I'm not a C++ user so I'm unable to prepare a demonstration example. The pygeos issue I originally filled (pygeos/pygeos#195) has some additional information and demo python scripts (both pygeos and shapely). While workaround were easily identified for our usage, we think this issue might still be worth investigating.

**Comment by dr-jts** [comment] 2020-09-21 20:04
The reason that `difference(lines, polygon)` runs so slowly is that the overlay algorithm in GEOS computes the fully-noded topology graph of **all** the inputs before determining the result of the overlay. As pointed out above, the lines dataset contains a very large number of self-intersections. This requires substantial processing to node. (Consider that the input contains only 100 lines with 138K points, while the difference output contains over **250K noded lines** with **over 600K points**!)

This is by design - noding and topology building is a core function of the overlay algorithm. If noding the full input is not desired, then simply compute the difference piecewise on the set of lines and (if needed) combine the result. As noted above, a spatial index can be used, although for this input I'm not sure it's necessary.

I also point out that self-intersecting LineStrings are valid according to the OGC spec. That is not a factor in this case.

It does seem to be the case that the current GEOS overlay algorithm has a hard time processing this case. Happily, there is a completely new GEOS overlay implementation which is going to be released [shortly](https://lists.osgeo.org/pipermail/geos-devel/2020-September/009670.html), and it appears to handle this case much better (less memory and faster).

**Comment by pramsey** [comment] 2021-09-10 23:31
Since the new release is out (for a year now) I'm closing.

**Closed by pramsey** 2021-09-10 23:31 UTC
