### ISSUE TITLE
Buffer analysis error

### ISSUE THREAD

**Issue by tantelu** [libgeos/geos#517] opened 2021-12-03 09:51 UTC
CoordinateArraySequence* cas = new CoordinateArraySequence();
	cas->add(Coordinate(-1, 1, 0));
	cas->add(Coordinate(1, 1, 0));
	cas->add(Coordinate(1, -1, 0));
	cas->add(Coordinate(-1, -1, 0));
	auto line = GeometryFactory::getDefaultInstance()->createLineString(cas);
	auto pt = line->buffer(0.1, 2, 3);

![image](https://user-images.githubusercontent.com/29174485/144582247-33d61e22-8242-4d97-aac3-99eb84e967dc.png)

i run the code in win10
somebody else can help me test it?

**Comment by tantelu** [comment] 2021-12-03 12:07
# the code segment in TemplateSTRtree.h
  ------------------     
         numItems = nodes.size();
        // compute final size of tree and set it aside in a single
        // block of memory
        auto finalSize = treeSize(numItems);
        nodes.reserve(finalSize);

        // begin and end define a range of nodes needing parents
        auto begin = nodes.begin();
        auto end = nodes.end();

        while (std::distance(begin, end) > 1) {
            createParentNodes(begin, end);
            begin = end; // parents just added become children in the next round
            end = nodes.end();
        }
-----------------------------
when put a element in 'nodes'  ,  the end iterator is invalid  
so  'std::distance(begin, end) > 1' is a bug
i change it to 
--------
while (std::distance(begin, end) > 1) {
                        auto endpre = end - 1;
                        createParentNodes(begin, end);
                        begin = endpre + 1; // parents just added become children in the next round
                        end = nodes.end();
                    }
--------
it can work correct when 'nodes' is not emtpy

**Comment by pramsey** [comment] 2021-12-03 16:34
I think this might be a duplicate of the issue fixed in #508, are you running from a release or from main? The fix has not been released yet.

**Closed** 2022-01-11 22:46 UTC
Labels: Feedback Requested
