### ISSUE TITLE
Topology preserving simplification produces invalid multipolygon in 3.13.0

### ISSUE THREAD

**Issue by ylieder** [libgeos/geos#1190] opened 2024-11-10 11:08 UTC
Hello,

the valid multipolygon given below produces an invalid polygon after simplification in geos 3.13.0. In shapely 2.0.6 (which uses geos 3.11.4), the polygon is valid after simplification and looks also different.

Maybe it is related to the [changes](https://github.com/libgeos/geos/issues/1180) of the simplifier made in 3.13.0.

# Steps to reproduce:
```
❯ geos-config --version
3.13.0

❯ geosop -a input_polygon.wkt isValid
true

❯ geosop -a input_polygon.wkt simplifyTP 0.1
MULTIPOLYGON (((689.300102 5733.615673, 689.46186 5733.617409, 689.458981 5733.646089, 689.300102 5733.615673)), ((689.488158 5733.746304, 689.23796 5733.680098, 689.253227 5733.613915, 689.679568 5733.588383, 689.488158 5733.746304)))

❯ geosop -a input_polygon.wkt simplifyTP 0.1 | geosop -a - isValid
false
```
The input polygon:
```
MULTIPOLYGON (((689.333567 5733.539399, 689.335754 5733.534616, 689.338414 5733.528808, 689.33878 5733.528007, 689.339295 5733.526884, 689.343502 5733.53001, 689.364663 5733.545752, 689.376307 5733.554418, 689.390955 5733.565421, 689.401872 5733.573364, 689.449408 5733.60852, 689.449575 5733.609988, 689.448713 5733.61218, 689.450278 5733.61347, 689.452433 5733.614861, 689.46186 5733.617409, 689.455824 5733.632539, 689.45904 5733.635609, 689.458981 5733.646089, 689.447304 5733.646901, 689.434534 5733.647491, 689.40922 5733.642907, 689.320546 5733.620868, 689.302885 5733.61643, 689.301333 5733.616007, 689.300102 5733.615673, 689.30643 5733.600999, 689.310466 5733.59152, 689.318738 5733.572875, 689.321855 5733.565499, 689.326805 5733.554307, 689.331263 5733.544428, 689.333567 5733.539399)), ((689.488158 5733.746304, 689.48107 5733.739996, 689.48063 5733.740474, 689.471494 5733.732342, 689.466433 5733.727847, 689.447733 5733.712239, 689.437049 5733.709591, 689.41159 5733.702871, 689.378682 5733.693749, 689.326133 5733.678786, 689.295154 5733.685694, 689.287831 5733.686429, 689.286696 5733.686462, 689.276607 5733.686729, 689.260516 5733.685316, 689.23796 5733.680098, 689.242448 5733.667716, 689.254068 5733.635631, 689.258549 5733.623249, 689.258994 5733.622025, 689.250964 5733.620168, 689.253227 5733.613915, 689.275563 5733.619278, 689.296484 5733.624484, 689.390817 5733.647146, 689.390653 5733.651596, 689.453214 5733.669852, 689.456439 5733.665903, 689.460803 5733.666259, 689.464728 5733.671599, 689.467162 5733.67151, 689.540893 5733.636477, 689.558474 5733.626375, 689.571555 5733.61169, 689.606543 5733.552572, 689.611314 5733.553806, 689.635373 5733.569048, 689.64516 5733.573331, 689.679568 5733.588383, 689.673051 5733.603569, 689.688729 5733.608809, 689.674072 5733.643497, 689.683092 5733.646634, 689.673195 5733.672489, 689.645333 5733.669085, 689.635065 5733.690144, 689.62618 5733.712606, 689.601513 5733.71146, 689.592455 5733.71255, 689.586614 5733.714174, 689.580087 5733.717612, 689.570186 5733.725689, 689.557792 5733.763414, 689.55541 5733.762513, 689.554633 5733.762213, 689.547236 5733.765316, 689.545484 5733.767219, 689.506862 5733.759554, 689.491458 5733.748451, 689.488158 5733.746304)))
```

## Screenshots
Input polygon
![image](https://github.com/user-attachments/assets/1b85b765-90c5-4ada-a5cc-6b4556fe6699)

Output (Shapely 2.0.6 with geos 3.11.4)
![image](https://github.com/user-attachments/assets/a3af8376-8425-4eef-8996-9bfaf0e5f346)

Output (geos 3.13.0)
![image](https://github.com/user-attachments/assets/884885a2-55c4-4693-b7b0-786a3fe3c348)

**Comment by dr-jts** [comment] 2024-11-10 21:13
As you suggest, this is due to a bug in the changes in #1012.  This was first revealed in #1180 (although in JTS, not GEOS). This has been fixed in https://github.com/locationtech/jts/pull/1096 and https://github.com/libgeos/geos/commit/d9d96a2e66ee3ff91c1498a0e4bcba7e6842b9f3 (and has been backported back to 3.11)  

Thanks for this case - it is a good one to add to the unit test suite.  Also, nice use of `geosop` for reporting the failure in an easily  reproducible way.

**Closed** 2024-11-26 00:22 UTC
Labels: Bug
