### ISSUE TITLE
Intersecting LINESTRINGs or POLYGONs creates MULTILINESTRING with multiple parts although not needed

### ISSUE THREAD

**Issue by agiudiceandrea** [libgeos/geos#1193] opened 2024-11-17 16:10 UTC
Using GEOS 3.13.0 (OSGeo4W):

```
geosop -a "LINESTRING (0 0, 1 0, 2 0)" -b "LINESTRING (0 0, 1 0, 2 0)" intersection
MULTILINESTRING ((0 0, 1 0), (1 0, 2 0))
```

The expected result should be `LINESTRING (0 0, 1 0, 2 0)`, instead.

**Comment by mwtoews** [comment] 2024-11-17 23:46
For what it's worth, a minor adjustment to the input geom yields a LineString:
```sh
$ geosop -a "LINESTRING (0 0, 1 0)" -b "LINESTRING (0 0, 1 0)" intersection
LINESTRING (0 0, 1 0)
```
so there is an inconsistency in how these similar cases are handled.

**Comment by pramsey** [comment] 2024-11-18 00:06
More edges results in more parts
```
./geosop -a "LINESTRING (0 0, 1 1, 2 2, 3 3)" -b "LINESTRING (0 0, 1 1, 2 2, 3 3)" intersection

MULTILINESTRING ((0 0, 1 1), (1 1, 2 2), (2 2, 3 3))
```

**Comment by dzakaTarik** [comment] 2024-11-22 10:43
Changing `STRICT_MODE_DEFAULT` (in `OverlayNG.h`) to true does not fix the issue.
Seems to me that this is just the way it works by design. 

For this specific case (first example that OP gave): when [creating](https://github.com/libgeos/geos/blob/ef84de66451723471d59cb22fac634fa861f939a/src/operation/overlayng/OverlayUtil.cpp#L285) resulting geometry we build geometry from two LineStrings (0 0, 1 0) and (1 0, 2 0). [Resulting type](https://github.dev/libgeos/geos/blob/ef84de66451723471d59cb22fac634fa861f939a/src/geom/GeometryFactory.cpp#L800), for a list of LineStrings, is a MultiLineString in [all cases](https://github.dev/libgeos/geos/blob/ef84de66451723471d59cb22fac634fa861f939a/src/geom/GeometryFactory.cpp#L781). There are no checks if these LineStrings can be merged to a single LineString in any way.

**Comment by dr-jts** [comment] 2024-11-22 20:20
This behaviour is by design.  The Overlay algorithm returns fully noded LineStrings.  

One reason for this is that it avoids a final step of computing a merged set of line edges.  If desired, this can be done as a post-processing step using [`LineMerger`](https://github.com/libgeos/geos/blob/main/src/operation/linemerge/LineMerger.cpp) or [`GEOSLineMerge`](https://libgeos.org/doxygen/geos__c_8h.html#aa1fc240c0d7b615365b24e8ee86ce57c).

**Comment by agiudiceandrea** [comment] 2024-11-22 21:14
Thanks for the explanation.

**Closed** 2024-11-22 22:01 UTC
Labels: Feedback Requested
